services:
  spa:
    build:
      dockerfile: ./frontend/Dockerfile
      target: dev
    command: npm run start
    volumes:
      - ./frontend/src:/code/src

  proxy:
    build:
      target: proxy
    volumes:
      - "./proxy/dev.nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - 3000:3001
