services:
  proxy:
    depends_on:
      - oauth2
    build:
      dockerfile: ./frontend/Dockerfile
      target: proxy-server
    secrets:
      - source: CERT_PUB
        target: localhost.pem
      - source: CERT_KEY
        target: localhost-key.pem
    volumes:
      - "./proxy/prod.nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - "443:8443"
      - "80:8080"
    
  oauth2:
    build:
      dockerfile: ./oauth2/Dockerfile
      target: oauth2
    environment:
      - OAUTH2_PROXY_CLIENT_ID=${CLIENT_ID}
      - OAUTH2_PROXY_COOKIE_DOMAINS=${SERVER_NAME}
      - OAUTH2_PROXY_WHITELIST_DOMAINS=${SERVER_NAME}
      - OAUTH2_PROXY_REDIRECT_URL=https://${SERVER_NAME}/oauth2/callback
    volumes:
      - "./oauth2/oauth2-proxy.cfg:/oauth2-proxy.cfg:ro"
    secrets:
      - CLIENT_SECRET

secrets:
  CERT_PUB:
    file: ./secrets/localhost.pem
  CERT_KEY:
    file: ./secrets/localhost-key.pem
  CLIENT_SECRET:
    file: ./secrets/CLIENT_SECRET.txt
