services:
  proxy:
    depends_on:
      - oauth2
    build:
      dockerfile: ./src/Dockerfile
      target: proxy
    secrets:
      - source: CERT_PUB
        target: localhost.pem
      - source: CERT_KEY
        target: localhost-key.pem
    volumes:
      - "./proxy/prod.nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "443:8443"
      - "80:8080"
    
  oauth2:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    command: --config /oauth2-proxy.cfg
    environment:
      - OAUTH2_PROXY_CLIENT_ID=${OAUTH2_PROXY_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH2_PROXY_CLIENT_SECRET}
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
    volumes:
      - "./oauth2/oauth2-proxy.cfg:/oauth2-proxy.cfg"

secrets:
  CERT_PUB:
    file: ./secrets/localhost.pem
  CERT_KEY:
    file: ./secrets/localhost-key.pem
