services:
  spa:
    build:
      dockerfile: ./src/Dockerfile
      target: dev
    command: npm run start
    volumes:
      - ./src:/src/src
    ports:
      - 3000

  proxy:
    volumes:
      - "./proxy/dev.nginx.conf:/etc/nginx/conf.d/default.conf"
